sudo: false

language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

compiler:
  - g++

# env:
#   - WAF_BUILD=build_release
#   - WAF_BUILD=build_debug

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - pip install cpp-coveralls --user `whoami`
  - source ./travis/gtest.sh

script:
  - python waf configure
  - python waf build_release

after_success:
  - coveralls --gcov "gcov-4.9" --exclude test --exclude googletest --root . --build-root ".build/release" --gcov-options '\-lp'

after_failure:
  - cat ./.build/config.log

# notifications:
#   email: false
