sudo: false

language: cpp

env:
  global:
   - secure: "A6kNzImxJfKIoYsPSMvPF2yIeeIk0uwN5YNo3fDFrviAeU9jva42YDkpaBvM457Yw5ZNq9srRZWytLUf8hX9H5G+C0biUSH/n1MAwPNwOMw8SkMep8IJ1jC+kabxvUBEi0x7ApJ6PweJXv5e4QV6dc/aBPjQgzmpw36gVE3tr+6hYNplRv23IShyO6Nza3CGydolNWILtYwoCddoDlpWkKO1asJZKUCEqSmBiZw4B8OPzuADiq3EJmbo6fZOUlewxNQOK1hG2DwW2WnsRXvRSrx/mTHcTNy5+duVJcNTvp3XWISvJboYdvR2+0+9GDJtXcVTFGB94v63dKRDoHqsVSDmaovRF7huufjzC4CW51cLyZ2RH4TYZ2Di7kCRrU06dW40ia83aGJBXgX6LF48Ugxx1h8bmQo5PIeOBWkVJ/QZductCV9dBenHngoIbBdzD2CWyFcz9FMUn2rK+BYsKYk6AIq36CoRpkKuLWZNBav53ky4IiBpQc/VbTOOgLAihiueR9/s+mPZpAlzDAkiIUr4NFyLRIItX1tFQ53xHw4OUElITq0DIGPcjO+C1OYfm3siapL0RQVJrRdvMRM9cxxu/uyOPdbFwehSJQruASMmBbfeg/5P2CKdWGojNazO+AcRXogXtpzLwBDcpo2il/Lesv1QKoxAxScKQeFhOYg="

cache:
  apt: true
  directories:
    - .build

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
  coverity_scan:
    project:
      name: "srouquette/kodama"
      description: "multi-threaded orthodox file manager"
    notification_email: srouquette@gmail.com
    build_command_prepend: "python waf configure"
    build_command: "python waf build_debug"
    branch_pattern: develop

compiler:
  - g++

# env:
#   - WAF_BUILD=build_release
#   - WAF_BUILD=build_debug

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - pip install cpp-coveralls --user `whoami`
  - source ./travis/gtest.sh

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then python waf configure ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then python waf build_debug ; fi

after_success:
  - coveralls --gcov "gcov-4.9" --exclude test --exclude googletest --root . --build-root ".build/debug" --gcov-options '\-lp'

after_failure:
  - cat ./.build/config.log

# notifications:
#   email: false
